name: Publish Python Package to PyPI

on:
  push:
    branches:
      - master   # Trigger when pushing to the master branch
    tags:
      - 'v*'     # Also trigger when a version tag (e.g., v1.0.0) is pushed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # Set desired Python version

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload dist/* --skip-existing  # Upload to PyPI, skip existing versions
